{{- if .Values.opsdroid.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: opsdroid-{{ .Release.Name }}
  annotations:
    {{- range $key, $value := .Values.opsdroid.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ $.Values.opsdroid.ingress.ingressClassName }}
  rules:
    {{- range $host := .Values.opsdroid.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: opsdroid-{{ $.Release.Name }}
                port:
                  number: {{ $.Values.opsdroid.service.port }}
    {{- end -}}
  {{- if .Values.opsdroid.ingress.tls }}
  tls:
{{ toYaml .Values.opsdroid.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
